### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by cord** [dcasia/nova-inline-morph-to#10]
Thanks again for this great package.

Am struggling with the following situation for some hours... the GUI works, when saving I get following exception

```
"message": "Trying to access array offset on value of type null",
"exception": "ErrorException",
"file": "/vendor/digital-creative/nova-inline-morph-to/src/InlineMorphTo.php",
"line": 285,
```

Debugging shows that
`$this->meta[ 'resources' ]->where('className', $resourceClass)->first()` 

returns null (but $resourceClass is valid).

Any idea what the issue might be?

**Comment by milewski** [comment]
does `dd($this->meta[ 'resources' ])` returns an empty array? or it also contains the `dd($resourceClass)` in it?

**Comment by milewski** [comment]
I just tried seems to be working fine, double-check that the `->types([])` are all Nova\Resource class not Model class, and that you are using the correct trait `HasInlineMorphToFields`

**Comment by cord** [comment]
thanks for your help again - the reason was being blind and having assigned the wrong model class
