### ISSUE TITLE
Read only morphable type?

### ISSUE THREAD

**Issue by cord** [dcasia/nova-inline-morph-to#16]
Just released https://github.com/Nova-BI/nova-databoards which makes heavy use of your great packages.

I understand the morphable type is read-only in edit mode on purpose to secure a valid data structure. However when having a morphable which has a morphable the 2nd level morphable type is not read-only. Is this a valid behaviour?

![Laravel 2020-07-01 11-21-42](https://user-images.githubusercontent.com/158588/86227365-3314b780-bb8d-11ea-9807-cb0f8a2c2b46.png)

**Comment by milewski** [comment]
Uhm that's definitely a bug! I'm a bit short in time right now to work on a fix for this, as soon as I get a chance I will go and try to have a look at that BI package and fix this bug, it is looking nice thou 👍

**Comment by cord** [comment]
@milewski just send you a mail
